import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Providers from "@/components/Providers"; // ✅ Import du composant Provider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
