const products = [
    {
        id: 9991,
        civility: "M",
        userName: "SachaDresseTout",
        name: "Sacha",
        familyName: "Dressesa",
        password: "allo",      
        address: "Le meilleur dresseur, 75010 Paris, France",  
        category: "admin",
        mobile: '06 06 06 06 06',
        mail: 'meilleurdresseur@pokemon.fr',
    },
    {
        id: 9992,
        civility: "M",
        userName: "PikaPika",
        name: "Pikachu",
        familyName: "Pokemon Electro", 
        password: "allo",             
        address: '2 rue des pokemons, 94310 ORLY, France',
        category: "user",
        mobile: '06 22 22 22 22',
        mail: 'pikachu@pokemon.fr',
    },
    {
        id: 9993,
        civility: "M",
        userName: "Jtebrule",
        name: "Salamèche",
        familyName: "Pokemon Feu",   
        password: "allo",           
        address: '3 rue des pokemons, 22310 Lisbonne, Portugal ',
        city: 'Lisbonne',
        zip: '22310',
        country: 'Portugal', 
        category: "user",
        mobile: '06 33 33 33 33',
        mail: 'salameche@pokemon.fr',
    },
    {
        id: 9994,
        civility: "Melle",
        userName: "Mouilletout",
        name: "Carapuce",
        familyName: "Pokemon Eau",
        password: "allo",              
        address: '3 rue des pokemons, 94310 Dakar, Senegal',
        city: 'Dakar',
        zip: '94310',
        country: 'Sénégal', 
        category: "user",
        mobile: '06 44 44 44 44',
        mail: 'carapuce@pokemon.fr',
    },
];

export default products;
