const products = [
    {
        id: 9991,
        civility: "M",
        userName: "SachaDresseTout",
        name: "Sacha",
        familyName: "Le meilleur dresseur",  
        password: "allo",      
        address: '1 rue des dresseurs, 94XXX Ahouuu',
        category: "admin",
        mobile: '06 06 06 06 06',
        mail: 'meilleurdresseur@pokemon.fr',
    },
    {
        id: 9992,
        civility: "M",
        userName: "PikaPika",
        name: "Pikachu",
        familyName: "Pokemon Electro", 
        password: "allo",             
        address: '2 rue des pokemons, 94XXX Ahouuu',
        category: "user",
        mobile: '06 22 22 22 22',
        mail: 'pikachu@pokemon.fr',
    },
    {
        id: 9993,
        civility: "M",
        userName: "Jtebrule",
        name: "Salamèche",
        familyName: "Pokemon Feu",   
        password: "allo",           
        address: '3 rue des pokemons, 94XXX Ahouuu',
        category: "user",
        mobile: '06 33 33 33 33',
        mail: 'salameche@pokemon.fr',
    },
    {
        id: 9994,
        civility: "Melle",
        userName: "Mouilletout",
        name: "Carapuce",
        familyName: "Pokemon Eau",
        password: "allo",              
        address: '3 rue des pokemons, 94XXX Ahouuu',
        category: "user",
        mobile: '06 44 44 44 44',
        mail: 'carapuce@pokemon.fr',
    },
    {
        id: 9995,
        civility: "Mme",
        userName: "LaBrige",
        name: "Brige",
        familyName: "Pichereau",
        password: "allo",              
        address: '3 rue Georges Baudelaire, 94310 Orly',
        category: "user",
        mobile: '06 44 44 44 44',
        mail: 'LaBrige@gmail.fr',
    },
];

export default products;
